# Generated by Django 3.1.7 on 2021-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='propic',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
