# Generated by Django 3.1.7 on 2021-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_propic_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='propic',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
