# Generated by Django 3.1.7 on 2021-05-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210515_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='female_only',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liguor_allowed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='male_only',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='no_smoking',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pets_allowed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='play_music',
        ),
        migrations.AddField(
            model_name='ride',
            name='female_only',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='liguor_allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='male_only',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='no_smoking',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='pets_allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='play_music',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
