# Generated by Django 3.1.7 on 2021-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_ride_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plate',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
