# Generated by Django 3.1.7 on 2021-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210516_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rider_mobile',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
